### ISSUE TITLE
Create a Navbar and Footer

### ISSUE THREAD

**Issue by NeuralFlux** [oss2019/crispy-ai#22]
Navbar will have the following items:
- [ ] Logo on left
- [ ] Home (redirects to login if not logged in)
- [ ] Courses (for user and admin)
- [ ] Users (for admin)
- [ ] Live (for user and admin)
- [ ] Logout (if logged in)

Footer will have:
- [ ] About page link
- [ ] Contribute link, which links to `oss2019/crispy-ai` repo

**Comment by vah-ini** [comment]
I would like to have this issue

**Comment by svp19** [comment]
Hey @vah-ini , I'm assigning the issue to you. Please do make sure it's responsive. You can use bootstrap 4 if you want.

**Comment by svp19** [comment]
#44 Helped fix this
