### ISSUE TITLE
Fix error ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by NeuralFlux** [oss2019/crispy-ai#24]
Currently, when we go to `localhost:8000`, there's an error saying `ERR_TOO_MANY_REDIRECTS`. This issue is to get it fixed. _Hint: Try Googling, it really helps_

**Comment by NeuralFlux** [comment]
@vedangj044 would you like me to assign this to you, even if it's just a / to fix?

**Comment by vedangj044** [comment]
As, i said on gitter this bug would be eliminated automatically if we create a base home page. So, please assign me that issue, and it's commit would close this as well as `base` home page issue.
