### ISSUE TITLE
Validate Email while User Registers

### ISSUE THREAD

**Issue by NeuralFlux** [oss2019/crispy-ai#29]
We cannot allow spam emails to come in. Hence, validate the emails of each user while registering. There are 2 kinds of validation, one which checks if such an email address exists and one which just checks for the syntax of the entered text (like abc@xyz.domain). **The former validation is preferred but if it's not possible to get that done, just the second one is enough.**

_Hint: You can do this while the form data is "cleaned"_

**Comment by ayush1999guptA** [comment]
This issue is taken cared of in my latest pull request
