### ISSUE TITLE
Add Email Confirmation for Registration

### ISSUE THREAD

**Issue by NeuralFlux** [oss2019/crispy-ai#30]
After #15 and #29 are completed, add an email confirmation feature to the registration procedure, to further filter the spam.

- So when a user registers, he should be shown a page saying "An email has been sent to your email ID, kindly go to that URL to confirm your account".
- If someone comes with an invalid link, display "There was some error validating this account, kindly try again"
- If someone comes with a proper link, display "Your account has been activated!" and activate their account.

**A few points to keep in mind while implementing this:**
- A user can login only if an attribute `is_active` is `True`. So if the verification fails, set this to `False`. Else, set it to `True`.

**Comment by ayush1999guptA** [comment]
Can I have this issue?

**Comment by NeuralFlux** [comment]
Sure

**Comment by bvishal8510** [comment]
@NeuralFlux is someone still working on this issue? If not may I work on this?

**Comment by NeuralFlux** [comment]
> @NeuralFlux is someone still working on this issue? If not may I work on this?

Done

**Comment by NeuralFlux** [comment]
> @NeuralFlux is someone still working on this issue? If not may I work on this?

Hey, I assigned you to it. Thanks for taking it up!

**Comment by sarthakvijayvergiya** [comment]
@NeuralFlux is someone still working on this issue? If not may I work on this?

**Comment by bvishal8510** [comment]
@sarthakvijayvergiya I am working on this. You may take up any other issue.

**Comment by svp19** [comment]
Issue resolved
