### ISSUE TITLE
Create a Lecture Model

### ISSUE THREAD

**Issue by svp19** [oss2019/crispy-ai#37]
Every Course has a bunch of lectures and it is this model that Crispy directly deals with.
Create a `LectureModel` in `admin/models.py`
Some of the fields it might have:
- Lecture No.
- Title
- Live Transcript(textfield)
- Summary(textfield)
- Tags
- OneToOne Field to Course model

Feel free to add more!

**Comment by vedangj044** [comment]
I would work on this.
